# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DojoNinjas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='Default'),
            preserve_default=False,
        ),
    ]
